""" Vundle.vim """
filetype off			        " required by vundle
set nocompatible 		        " required by vundle (Be iMproved)

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" plugin on GitHub repo
" Plugin 'altercation/vim-colors-solarized'
Plugin 'Valloric/YouCompleteMe'
Plugin 'vim-scripts/ctags.vim'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/nerdcommenter'
Plugin 'mattn/emmet-vim'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'chase/vim-ansible-yaml'
Plugin 'vitalk/vim-simple-todo'
" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'colorsupport.vim'
" Plugin 'xoria256.vim'

" All of your Plugins must be added before the following line
call vundle#end()               " required by vundle
filetype plugin indent on       " required

" Basic configuration
syntax on
set backspace=indent,eol,start  " make backspace behave in a sane manner.
set encoding=utf-8              " set encoding
set number                      " display line numbers
set showmatch                   " highlights matching brackets
set autoindent                  " if you're indented, new lines will also be indented
set smartindent                 " automatically indents lines after opening a bracket
set tabstop=4                   " how much space Vim gives to a tab
set shiftwidth=4
set smarttab                    " improves tabbing
set expandtab                   " insert space characters whenever the tab key is pressed
set laststatus=2                " statusbar always visible for Powerline
set pastetoggle=<F2>            " better pasting from external sources

" Change the Leader key to space
let mapleader=" "

" Mappings and shortcuts
" Basics
inoremap jk <ESC>  

" Control shortcuts
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Disable arrow keys in NORMAL mode
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop> 

" Disable arrow keys in VISUAL mode
vnoremap <up> <nop>
vnoremap <down> <nop>
vnoremap <left> <nop>
vnoremap <right> <nop> 

" Aesthetics
colorscheme getfresh

" Add empty lines without entering insert mode
nmap <S-Enter> O<Esc>
nmap <CR> o<Esc>

" highlight the status bar when in insert mode
if version >= 700
    au InsertLeave * hi StatusLine ctermfg=235 ctermbg=2
    au InsertEnter * hi StatusLine ctermbg=240 ctermfg=12
endif
