#! /bin/dash

FIRST_DESK=One
REMAINING_DESKS='Two Three Four Five Six Seven Eight Nine Ten'
bspc rename Desktop01 $FIRST_DESK
bspc add $REMAINING_DESKS
#bspc layout monocle $FIRST_DESK $REMAINING_DESKS

# WWW
bspc rule Firefox One

# DEV
bspc rule Upgrade Two

# FILE
bspc rule Geeqie Three floating
bspc rule Thunar Three

# CHAT
bspc rule Weechat Four
bspc rule Skype Four

# VAR
bspc rule Ncmpcpp Five
bspc rule Rtorrent Five

# GUI
bspc rule Gimp Six floating
bspc rule Inkscape Six floating

bspc set border_width 2
bspc set window_gap 10
bspc set bottom_padding 20

#COLORS
bspc set focused_border_color "#0DABFF"

bspc set borderless_monocle true
bspc set gapless_monocle true
bspc set focus_follows_pointer true
bspc set adaptative_raise true
#bspc set apply_shadow_property true

if [ -e "$BSPWM_BACKUP" ] ; then
	bspc restore "$BSPWM_BACKUP"
	rm "$BSPWM_BACKUP"
else
	bspc adopt_orphans
fi

pgrep -x compton > /dev/null || compton --respect-prop-shadow -bc -t -8 -l -9 -r 6 -o 0.7
