# Nord dark theme
set $black      #2e3440
set $grey       #3b4252
set $red        #bf616a
set $green      #a3be8c
set $yellow     #ebcb8b
set $blue       #81a1c1
set $magenta    #b48ead
set $cyan       #88c0d0
set $white      #e5e9f0

set $focused   #7a854c
set $urgent    #ebcb8b


#class                    backgr.   border    text
client.focused            $focused  $focused  $black
client.focused_inactive   #3C4C87   #3C4C87   #b9c8d1
client.unfocused          $black    $black    $white
client.urgent             $urgent   $urgent   $black
client.background         $black
