# Polar light theme (based on Nord with reversed palette)
# https://github.com/mtyn/polar
set $black      #2e3440
set $grey       #3b4252
set $red        #bf616a
set $green      #a3be8c
set $yellow     #ebcb8b
set $blue       #81a1c1
set $magenta    #b48ead
set $cyan       #88c0d0
set $white      #e5e9f0

set $focused   #7a854c
set $urgent    #ebcb8b


#class                    backgr.   border    text
client.focused            $focused  $focused  $white
client.focused_inactive   #ccd0da   #ccd0da   $grey
client.unfocused          $white    $white    $grey
client.urgent             $urgent   $urgent   $white
client.background         #ffffff
